version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'

  backend:
    image: backend
    build: ./api
    environment:
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_PORT: '5432'
      DB_HOST: db
    restart: on-failure
    entrypoint: ./backend/start.sh
    depends_on:
      - db

  worker:
    image: backend
    environment:
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_PORT: '5432'
      DB_HOST: db
    command: python3 worker.py
    restart: on-failure
    depends_on:
      - db

volumes:
  db:
